<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Your Calculations From Loistic</title>
</head>
<body style="font-family:ProximaNova-Regular, Arial,Helvetica,sans-serif;">
<table cellspacing="0" cellpadding="0" border="0" style="background-color:#f1f1f1;width:600px;" align="center">
    <tr>
        <td>
            <table cellpadding="0" cellspacing="0" border="0" align="center" style="padding-top:35px;width:90%;">
                <tr>
                    <td>
                        <table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="border-bottom: solid 1px #D3D3D3">
                            <tr>
                                <td style="padding-left:15px;" width="50%">
                                    <img width="200" height="47" src="http://lojistic.com/images/lojistic-logo.png" alt="Lojistic">
                                </td>
                                <td width="50%">
                                    <a style="font-size:24px;color:#353535;text-decoration:none;float:right;padding-top:5px;" rel="nofollow" href="tel:18007835753">
                                        (800) 783-5753
                                    </a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="font-size:20px;font-weight:bold;padding-bottom:25px;padding-top:35px;">
                        Hello {{ $firstName }},
                    </td>
                </tr>
                <tr>
                    <td style="font-size:16px;line-height:24px;color:#353535;">Attached you will find a copy of the report generated by the  {{ $calculator }} from our website. Our team of carrier experts is available to help answer questions about this report and assist with the use of our web tools. We are also available to assist with more complex inquires and carrier analysis. The following list provides quick reference to some of the common analytic projects that we conduct for our customers:
                    </td>
                </tr>
                <tr>
                    <td style="padding-top:15px;font-size:16px;line-height:20px;color:#353535;">
                        <ul>
                            <li>Service Level Optimization (SLO) Analysis </li>
                            <li>Annual General Price Increase (GPI) Analysis </li>
                            <li>Fee Reduction Analysis </li>
                            <li>Carrier Rate Analysis </li>
                            <li>UPS vs FedEx vs Regional Carrier Analysis </li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table cellpadding="15" cellspacing="0" border="0" width="80%" align="center" style="padding-top:20px;padding-bottom:20px;">
                            <tr>
                                <td align="center" style="display:block;border-bottom:4px solid #CF7E21;background-color:#F6921E">
                                    @if($calculator == 'Carrier Rates Calculator')
                                        <a rel="nofollow" href="{{ url('shipping-costs-calculators/fedex-ups-rates-calculator') }}" style="text-decoration:none;color:#ffffff;font-size:24px;">
                                            Click Here To Run Another Custom Rate Calculation
                                        </a>
                                    @else
                                        <a rel="nofollow" href="{{ url('shipping-costs-calculators/fedex-ups-rate-comparison-tool') }}" style="text-decoration:none;color:#ffffff;font-size:24px;">
                                            Click Here To Run Another Rate Comparison
                                        </a>
                                    @endif

                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="font-size:18px;line-height:20px;color:#02334D;padding-top:20px;font-weight:bold;">
                        Lojistic is here to help!
                    </td>
                </tr>
                <tr>
                    <td style="font-size:18px;line-height:20px;color:#02334D;padding-top:5px;font-weight:bold;">
                        Call Us: <a style="color:#02334D;text-decoration:none;" rel="nofollow" href="tel:18007835753">(800) 783-5753</a>
                    </td>
                </tr>
                <tr>
                    <td style="font-size:18px;line-height:20px;color:#02334D;padding-top:5px;font-weight:bold;">
                        <a rel="nofollow" href="http://www.lojistic.com" style="color:#02334D">www.Lojistic.com </a></td>
                </tr>
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0" border="0" width="100%">
                            <tr>
                                <td align="center" style="padding-top:45px;"><a rel="nofollow" href="http://www.Lojistic.com"><img width="121" height="28" src="http://lojistic.com/images/lojistic-logo.png" alt="Lojistic">
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td align="center" style="font-size:13px;color:#6F6F6F;padding-top:5px;padding-bottom:40px;">
                                    <a style="color:#6F6F6F;text-decoration:none;" rel="nofollow" href="http://www.lojistic.com">Lojistic | 3200 Park Center Drive | Suite 500 | Costa Mesa, CA 92626
                                    </a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>