@extends('layouts.flat')
@section('meta')
    @include('layouts.inc.flat-meta', [
        'title'       => 'Customer Testimonials & Success - Lojistic',
        'description' => 'Read freight audit testimonials from satisfied customers who saved money and reduced shipping costs.',
        'keywords'    => 'Freight Audit, Shipping Costs',
    ])
@overwrite
@section('content')

    <section class="white">
        <div class="container">
            <h1 class="text-center">
                <i class="eloji eloji-blog"></i>&nbsp;
                Customer Testimonials
            </h1>
            <p class="text-center">The following are testimonials from some of our customers:</p>

            <blockquote>
                <q>
                    Before using the services of Lojistic we had been convinced our carrier contract incentives were
                    great.
                    Their free contract analysis identified a significant opportunity to improve our pricing. We used
                    their
                    negotiation services, which resulted in a multiple six figure savings in our annual small parcel
                    costs.
                </q>
                <cite>
                    <span class="name">Javier S.</span> -
                    <span class="title">President</span>
                    <span class="company">Healthcare &amp; Pharmaceutical Industry</span>
                </cite>
            </blockquote>

            <blockquote>
                <q>
                    Until you began to audit our bills we had no idea there were so many late deliveries and billing
                    errors
                    on our carrier invoices that were eligible for refund. Your shipping audit services are essential
                    for
                    all high volume shippers. We consider you to be critical ally in our logistics cost management.
                </q>
                <cite>
                    <span class="name">Jeff S.</span> -
                    <span class="title">VP of Operations</span>
                    <span class="company">Printing &amp; Fulfillment Industry</span>
                </cite>
            </blockquote>


            <blockquote>
                <q>
                    In addition to the cost savings generated by Lojistic's audit and negotiation services, the
                    Data.Lojistic tool has been invaluable to our team in managing carrier relationships and
                    illuminating
                    additional operational improvement and cost reduction opportunities.
                </q>
                <cite>
                    <span class="name">Carter S.</span> -
                    <span class="title">President/CEO</span>
                    <span class="company">Computers &amp; Electronics Industry</span>
                </cite>
            </blockquote>


            <blockquote>
                <q>
                    Lojistic's customized GL coding solutions have eliminated 15 - 20 hours of work each week for our
                    accounting department. Their team has been extremely helpful and pleasant to work with as we have
                    refined our coding parameters. This value ad solution is reason enough to retain their services.
                </q>
                <cite>
                    <span class="name">Robert L.</span> -
                    <span class="title">COO/CFO</span>
                    <span class="company">Online Retail &amp; Wholesale Industry</span>
                </cite>
            </blockquote>

            <blockquote>
                <q>
                    The carrier negotiation process that you helped us through has saved us way more than I anticipated
                    and even strengthened our relationship with UPS and FedEx (like you said it would), which I would
                    have
                    not have thought possible under the circumstances! And now I promise that in return we will try very
                    hard to get our biggest vendor to at least grant you a meeting regarding saving them money too. They
                    would
                    be a great account for you and you deserve it.
                </q>
                <cite>
                    <span class="name">Dave M.</span> -
                    <span class="title">Director of Distribution</span>
                    <span class="company">Automotive Parts Manufacturer</span>
                </cite>
            </blockquote>
            <blockquote>
                <q>
                    I can&rsquo;t begin to thank you enough for all the help you have given us on this project. You were
                    just so easy to work with and I am sure we could not have achieved the savings we did without having
                    you
                    as the “inside person” who knows UPS. You never made me feel rushed and spent tons of time coaching
                    the
                    process. You made it practically effortless and saved us a ton of money. Thank you!
                </q>
                <cite>
                    <span class="name">Dani N.</span> -
                    <span class="title">Vice President</span>
                    <span class="company">Construction Supplies Wholesaler</span>
                </cite>
            </blockquote>
            <blockquote>
                <q>
                    I am incredibly pleased with the money you are “finding” for us in late shipments and carrier
                    billing
                    errors. It&rsquo;s not a pot of gold that&rsquo;s showing up at our door every week, but it&rsquo;s
                    much
                    more than I would have thought and has certainly been adding up.
                </q>
                <cite>
                    <span class="name">Jeff M.</span> -
                    <span class="title">Vice President</span>
                    <span class="company">Healthcare Parts Manufacturer</span>
                </cite>
            </blockquote>
            <blockquote>
                <q>
                    We thought our internal bill and service audit was catching all late deliveries and billing errors.
                    Lojistic offered a no obligation trail of their audit solution. Their services consistently produce
                    200
                    - 300% more refunds than we were generating…PLUS we have access to dozens of very useful management
                    reports from their online reporting tool.
                </q>
                <cite>
                    <span class="name">Brad J.</span> -
                    <span class="title">CFO</span>
                    <span class="company">Apparel Industry</span>
                </cite>
            </blockquote>


            <p>Customer references are available upon request to help you further research our solutions: <strong><a
                            href="mailto:info@lojistic.com">info@lojistic.com</a></strong></p>
        </div>
    </section>

@stop