@extends('layouts.flat')
@section('meta')
    @include('layouts.inc.flat-meta', [
        'title'       => 'Reduce Freight Shipping Pricing - Lojistic',
        'description' => 'Lojistic\'s shipping audit pricing model ensures that you never pay too much for lower freight shipping prices.',
        'keywords'    => 'freight shipping prices, audit cost, cost audit, shipping pricing, freight shipping price',
    ])
@overwrite
@section('styles')
    {!!  Html::style('css/pages/pricing.css')  !!}
@stop
@section('content')
    <section>
        <div class="container">
            <article>
                <h2>Reduce Freight Shipping Pricing</h2>

                <p>
                    Lojistic's solutions will produce measurable cost savings in your various
                    shipping contracts. Our compensation is typically limited to a contingent share
                    of the actual savings generated by our freight management services.
                </p>

                <p>
                    In that way, clients benefit from no-cost service implementations and are able to assess the
                    value of our solutions based upon real audit cost results. We make sure to engage
                    with clients where an opportunity for savings is highly probable, thus aligning
                    our motivation with our customer's success in achieving lower freight shipping
                    prices.
                </p>

                <div id='pricing-icons'>
                    <h3>Lojistic's Pricing Model Includes:</h3>

                    <div class='row'>
                        <div class="col-xs-4">
                            <a id="Pricing1" rel="nofollow" href="#"><span>Contingency Based Fees</span></a>
                        </div>
                        <div class="col-xs-4">
                            <a id="Pricing2" rel="nofollow" href="#"><span>Substantial Cost Savings</span></a>
                        </div>
                        <div class="col-xs-4">
                            <a id="Pricing3" rel="nofollow" href="#"><span>Easy Set Up & Implementation</span></a>
                        </div>
                    </div>
                    <div class='row'>
                        <div class="col-xs-4">
                            <a id="Pricing4" rel="nofollow" href="#"><span>Multi-Point Audit</span></a>
                        </div>
                        <div class="col-xs-4">
                            <a id="Pricing5" rel="nofollow" href="#"><span>Carrier Rate Analysis</span></a>
                        </div>
                        <div class="col-xs-4">
                            <a id="Pricing6" rel="nofollow" href="#"><span>Optimization Consultation</span></a>
                        </div>
                    </div>
                    <div class='row'>
                        <div class="col-xs-4">
                            <a id="Pricing7" rel="nofollow" href="#"><span>No Long Term Contract</span></a>
                        </div>
                        <div class="col-xs-4">
                            <a id="Pricing8" rel="nofollow" href="#"><span>Best In Class Support</span></a>
                        </div>
                        <div class="col-xs-4">
                            <a id="Pricing9" rel="nofollow" href="#"><span>Safe & Secure Data Centers</span></a>
                        </div>
                    </div>
                    <div class='row'>
                        <div class="col-xs-4">
                            <a id="Pricing10" rel="nofollow" href="#"><span>Reporting Dashboards</span></a>
                        </div>
                        <div class="col-xs-4">
                            <a id="Pricing11" rel="nofollow" href="#"><span>Reduced Admin Costs</span></a>
                        </div>
                        <div class="col-xs-4">
                            <a id="Pricing12" rel="nofollow" href="#"><span>Custom GL Coding</span></a>
                        </div>
                    </div>
                    <hr/>
                </div>
                <p>
                    When it comes to your cost, audit services for shipping will never exceed the
                    savings you receive from freight shipping price reductions. <a rel="nofollow" href="/parcel-audit">Parcel audit</a> charges
                    are only a percentage of the shipping pricing savings that your freight audit
                    services company is able to achieve. In other words, our payment is tied to the
                    reduction we are able to achieve for you in freight shipping prices. Cost audit
                    services from Lojistic are never tied to a long-term contract, which
                    means you are able to use our freight shipping price reduction service without
                    any big commitment.
                </p>

                <p>
                    Lojistic&rsquo;s pricing model increases the savings you enjoy on shipping
                    without negatively impacting your overhead. Should you have any questions about
                    your cost, audit processes, or anything else, feel free to contact us. We want to
                    do everything we can to lower your freight shipping prices.
                </p>
            </article>
        </div>
    </section>
    <script type='text/javasript' language='javascript'>
        $(document).ready(function () {
            $(document).on('resize', function () {
                $('#pricing-icons a').each(function () {
                    $(this).css('height', $(this).outerWidth());
                });
            });
            $(document).trigger('resize');
        });
    </script>
@stop